#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = random.randint(1, 1000)  # TODO: edit here
    P = [None for _ in range(T)]
    Q = [None for _ in range(T)]
    R = [None for _ in range(T)]
    for i in range(T):
        P[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        Q[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        R[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(T)
    for i in range(T):
        print(P[i], Q[i], R[i])

if __name__ == "__main__":
    main()
