#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: int, A: str) -> str:
def solve(N, X, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    A = input()
    a = solve(N, X, A)
    print(a)

if __name__ == '__main__':
    main()
