#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> Tuple[int, List[int], List[int], int]:
def solve(S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    e, f, g, h = solve(S)
    print(e, end=' ')
    for i in range(e):
        print(f[i])
        print(g[i], end=' ')
    print(h)

if __name__ == '__main__':
    main()
