#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(W: int) -> int:
def solve(W):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W = int(input())
    a = solve(W)
    print(a)

if __name__ == '__main__':
    main()
