#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: int, d: int, e: int, f: int, g: List[str]) -> int:
def solve(a, b, c, d, e, f, g):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    g = [None for _ in range(a)]
    c, d = map(int, input().split())
    e, f = map(int, input().split())
    for i in range(a):
        g[i] = input()
    a1 = solve(a, b, c, d, e, f, g)
    print(a1)

if __name__ == '__main__':
    main()
