#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: List[int], Y: List[int], Q: int, a: List[int], b: List[int], c: List[int], d: List[int]) -> List[str]:
def solve(N, X, Y, Q, a, b, c, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    Q = int(input())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    c = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        a[i], b[i], c[i], d[i] = map(int, input().split())
    e = solve(N, X, Y, Q, a, b, c, d)
    for i in range(Q):
        print(e[i])

if __name__ == '__main__':
    main()
