#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, X: int, A: List[int]) -> str:
def solve(N, X, A):
    out_print = NO
    for i in range(N):
        if A[i] == X:
            out_print = YES
            break
    return out_print

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    X = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, X, A)
    print(a)

if __name__ == '__main__':
    main()
