#!/usr/bin/env python3
# from typing import *



# def solve(N: int, P: List[int], A: List[int]) -> int:
def solve(N, P, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    P = [None for _ in range(N)]
    A = [None for _ in range(N)]
    for i in range(N):
        P[i], A[i] = map(int, input().split())
    a = solve(N, P, A)
    print(a)

if __name__ == '__main__':
    main()
