#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(D - 1)]
    X = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(D - 1):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    Q = random.randint(1, 1000)  # TODO: edit here
    S = [None for _ in range(Q)]
    T = [None for _ in range(Q)]
    for i in range(Q):
        S[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        T[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(D)
    print(X)
    for i in range(D - 1):
        print(A[i])
    print(Q)
    for i in range(Q):
        print(S[i], T[i])

if __name__ == "__main__":
    main()
