#!/usr/bin/env python3
# from typing import *



# def solve(D: int, X: int, A: List[int], Q: int, S: List[int], T: List[int]) -> Tuple[int, List[int], List[str]]:
def solve(D, X, A, Q, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D = int(input())
    A = [None for _ in range(D - 1)]
    X = int(input())
    for i in range(D - 1):
        A[i] = int(input())
    Q = int(input())
    S = [None for _ in range(Q)]
    T = [None for _ in range(Q)]
    for i in range(Q):
        S[i], T[i] = map(int, input().split())
    n, a, b = solve(D, X, A, Q, S, T)
    print(n)
    print(*[a[i] for i in range(n)])
    print(*[b[i] for i in range(n)])

if __name__ == '__main__':
    main()
