#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10 ** 9)  # TODO: edit here
    b = random.randint(1, 10 ** 9)  # TODO: edit here
    c = random.randint(1, 10 ** 9)  # TODO: edit here
    d = random.randint(1, 1000)  # TODO: edit here
    f = [None for _ in range(d)]
    g = [None for _ in range(d)]
    h = [None for _ in range(d)]
    e = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(d):
        f[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        g[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        h[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(a, b)
    print(c, d, e)
    for i in range(d):
        print(f[i], g[i], h[i])

if __name__ == "__main__":
    main()
