#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: int, d: int, e: int, f: List[int], g: List[int], h: List[int]) -> Tuple[int, int]:
def solve(a, b, c, d, e, f, g, h):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    c, d, e = map(int, input().split())
    f = [None for _ in range(d)]
    g = [None for _ in range(d)]
    h = [None for _ in range(d)]
    for i in range(d):
        f[i], g[i], h[i] = map(int, input().split())
    m, n = solve(a, b, c, d, e, f, g, h)
    print(m)
    print(n)

if __name__ == '__main__':
    main()
