#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: str, S: List[str]) -> str:
def solve(N, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, S)
    print(a)

if __name__ == '__main__':
    main()
