#!/usr/bin/env python3
# from typing import *



# def solve(D: int, N: int, L: List[int], R: List[int], H: List[int]) -> int:
def solve(D, N, L, R, H):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    D, N = map(int, input().split())
    L = [None for _ in range(N)]
    R = [None for _ in range(N)]
    H = [None for _ in range(N)]
    for i in range(N):
        L[i], R[i], H[i] = map(int, input().split())
    a = solve(D, N, L, R, H)
    print(a)

if __name__ == '__main__':
    main()
