#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int64_t D, int N, const std::vector<int64_t> &L, const std::vector<int64_t> &R, const std::vector<int64_t> &H) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t D;
    int N;
    std::cin >> D >> N;
    std::vector<int64_t> L(N), R(N), H(N);
    REP (i, N) {
        std::cin >> L[i] >> R[i] >> H[i];
    }
    auto ans = solve(D, N, L, R, H);
    std::cout << ans << '\n';
    return 0;
}
