#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string FIRST = "First";
const std::string SECOND = "Second";
bool solve(int64_t N, int K, const std::vector<int64_t> &a) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int K;
    std::cin >> N >> K;
    std::vector<int64_t> a(K);
    REP (i, K) {
        std::cin >> a[i];
    }
    auto ans = solve(N, K, a);
    std::cout << (ans ? FIRST : SECOND) << '\n';
    return 0;
}
