#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, Q: int, S: str, a: List[int], b: List[int], c: List[int], d: List[int]) -> List[str]:
def solve(N, Q, S, a, b, c, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    c = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    S = input()
    for i in range(Q):
        a[i], b[i], c[i], d[i] = map(int, input().split())
    e = solve(N, Q, S, a, b, c, d)
    for i in range(Q):
        print(e[i])

if __name__ == '__main__':
    main()
