#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> Tuple[int, int, int, List[int]]:
def solve(N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    d, f, g, h = solve(N)
    print(d)
    print(f)
    print(g)
    for i in range(g):
        print(h[i])

if __name__ == '__main__':
    main()
