#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: str, M: str, C: List[List[str]]) -> str:
def solve(N, M, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    C = [[None for _ in range(N + 28)] for _ in range(N + 28)]
    for j in range(N + 4):
        for i in range(24):
            C[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, M, C)
    print(a)

if __name__ == '__main__':
    main()
