#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, A: List[int], B: List[int], C: List[int], D: List[int]) -> Tuple[int, int]:
def solve(N, M, A, B, C, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(M)]
    D = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i], C[i], D[i] = map(int, input().split())
    c, d = solve(N, M, A, B, C, D)
    print(c, d)

if __name__ == '__main__':
    main()
