#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(const std::vector<std::vector<auto> > &A) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    std::vector<std::vector<auto> > A(2 * N + 2, std::vector<auto>((2 * N + 2)));
    REP (j, N + 2) {
        REP (i, N) {
            std::cin >> A[i + j][i + j];
        }
    }
    auto ans = solve(A);
    std::cout << Q << '\n';
    REP (i, Q) {
        std::cout << X[i] << ' ' << Y[i] << ' ' << H[i] << '\n';
    }
    return 0;
}
