#!/usr/bin/env python3
# from typing import *



# def solve(X: int, Y: int) -> Tuple[str, List[str], List[str]]:
def solve(X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y = map(int, input().split())
    K, x, y = solve(X, Y)
    print(K)
    for i in range(K):
        print(x[i], y[i])

if __name__ == '__main__':
    main()
