#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(Q: int, X: List[int]) -> List[str]:
def solve(Q, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    X = [None for _ in range(Q)]
    for i in range(Q):
        X[i] = int(input())
    a = solve(Q, X)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
