#!/usr/bin/env python3
# from typing import *



# def solve(N: int, h: List[int]) -> Tuple[int, List[int]]:
def solve(N, h):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    h = [None for _ in range(N)]
    for i in range(N):
        h[i] = int(next(tokens))
    assert next(tokens, None) is None
    K, P = solve(N, h)
    print(K)
    print(*[P[i] for i in range(K)])

if __name__ == '__main__':
    main()
